### ISSUE TITLE
Should undfined fields return None rather than throwing an exception?

### ISSUE THREAD

**Issue by flound1129** [dgrtwo/ParsePy#114]
When I code with ParsePy, my code is invariably strewn with these:

    try:
        value = item.field
    except:
        value = ""

Shouldn't the library just return None if the field is undefined, rather than throwing an exception?

**Comment by dankrause** [comment]
If we returned None for an undefined field, there would be no way to tell whether or not a field existed, but contained the value `None`.

**Comment by flound1129** [comment]
Couldn't you throw an exception if the field didn't exist, and return None if the field existed and had no value?

**Comment by flound1129** [comment]
For comparison, the JS Api query.get("field") returns undefined whether the field exists or not.

**Comment by lullis** [comment]
But bear in mind that Javascript and Python are very different in how define types. What you are trying to do can work in Javascript because `undefined` is falsy, just like `null`. In Python, `None` is falsy, a non existent attribute is an exception.

But fear not: you can always use python's `getattr`. `value = getattr(item, 'field', None)` will do exactly what you want.
